### ISSUE TITLE
Update documentation to explain how to add Lua to your Xcode project

### ISSUE THREAD

**Issue by latenitefilms** [ggoraa/LuaKit#3]
This repo looks awesome - great work!

I'm pretty new to Swift and Xcode, and I'm having trouble actually getting things to work. I've added the LuaKit Swift package, and I expected it to include everything I need, but it seems I might need to manually add Lua or something?

<img width="427" alt="image" src="https://github.com/mock-foundation/luakit/assets/22286696/42cb149a-4cf1-4846-baa6-262cc8191d1c">

It would be great if the documentation could be updated for newbie's like me.

If I happen to work it out, I'll do a pull request to update documentation.

Thank you!

**Comment by latenitefilms** [comment]
Turns out I did just need to run `brew install lua`, but after doing that I had to restart Xcode and do a clean for it to actually work.

**Comment by levochkaa** [comment]
@latenitefilms АХХА
